# Generated by Django 5.2.7 on 2025-12-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_instructorinvite"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="instructorinvite",
            new_name="organizatio_email_9ff144_idx",
            old_name="organizati_email_c8f0dc_idx",
        ),
        migrations.RenameIndex(
            model_name="instructorinvite",
            new_name="organizatio_token_81e0f1_idx",
            old_name="organizati_token_0d3f07_idx",
        ),
    ]
