# Generated by Django 6.0 on 2025-12-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="purchase_type",
            field=models.CharField(
                choices=[("course", "Course"), ("certificate", "Certificate")],
                default="course",
                max_length=15,
            ),
        ),
    ]
