# Generated by Django 5.2.9 on 2026-01-15 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_section_created_at_section_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="section",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
