# Generated by Django 5.2.9 on 2026-01-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_section_created_at_alter_section_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsection",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="If checked, only students who purchased certificate can access this subsection",
            ),
        ),
    ]
