# Generated by Django 5.2.10 on 2026-04-10 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_subsection_is_locked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="section",
        ),
    ]
