# Generated by Django 5.2.14 on 2026-05-30 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_lesson_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='blockchain_block_number',
            field=models.PositiveIntegerField(blank=True, help_text='HieraChain Block Number', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='blockchain_status',
            field=models.CharField(choices=[('local', 'Local Only'), ('pending', 'Syncing to HieraChain'), ('synced', 'Synced on HieraChain'), ('failed', 'Sync Failed')], default='local', help_text='Status of certificate on HieraChain', max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, help_text='HieraChain Transaction Hash', max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='cryptographic_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of certificate content', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.subsection'),
        ),
    ]
