# Generated by Django 6.0 on 2025-12-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="profile",
            managers=[],
        ),
    ]
