# Generated by Django 5.2.9 on 2025-12-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="processor_transaction_id",
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="idempotency_key",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["user", "course", "purchase_type"], name="payments_user_course_purchase_idx"),
        ),
    ]
