# Generated by Django 5.2.7 on 2026-01-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_idempotency_processor"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_pa_user_id_d901ff_idx",
            old_name="payments_user_course_purchase_idx",
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("visa", "Visa"),
                    ("mastercard", "Mastercard"),
                    ("paypal", "PayPal"),
                    ("momo", "MoMo"),
                    ("zalopay", "ZaloPay"),
                    ("local_bank", "Local Bank (QR)"),
                ],
                max_length=20,
            ),
        ),
    ]
