# Generated by Django 5.2.9 on 2026-01-12 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0003_rename_payments_user_course_purchase_idx_payments_pa_user_id_d901ff_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Payment Created"),
                            ("status_change", "Status Changed"),
                            ("webhook_received", "Webhook Received"),
                            ("refund_initiated", "Refund Initiated"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("new_status", models.CharField(blank=True, max_length=20, null=True)),
                ("message", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["payment", "event_type"],
                        name="payments_pa_payment_ef6883_idx",
                    )
                ],
            },
        ),
    ]
