# Generated by Django 5.2.7 on 2025-10-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='expiration_date',
            field=models.DateTimeField(blank=True, help_text='Students must complete the course before this date to receive a certificate', null=True),
        ),
    ]
