# Generated by Django 5.2.7 on 2025-10-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_closing_date_course_opening_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Date and time when this module closes for students', null=True),
        ),
    ]
