# Generated by Django 5.2.7 on 2025-10-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_module_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='deadline',
        ),
        migrations.AddField(
            model_name='module',
            name='duration_days',
            field=models.PositiveIntegerField(default=7, help_text='Number of days students have to complete this module'),
        ),
    ]
