# Generated by Django 5.2.7 on 2025-10-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_module_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for certificate. Set to 0 if certificate is free (when course price > 0) or if course is free.', max_digits=10),
        ),
    ]
