# Generated by Django 5.2.7 on 2025-10-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_certificate_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='If checked, only students who purchased certificate can access this lesson'),
        ),
        migrations.AddField(
            model_name='module',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='If checked, only students who purchased certificate can access this module'),
        ),
    ]
