# Generated by Django 5.2.7 on 2025-11-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_question_question_type_alter_quiz_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of attempts allowed for this question (0 for unlimited)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
