# Generated by Django 5.2.7 on 2025-11-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_question_max_check_alter_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='max_attempts',
        ),
    ]
