# Generated by Django 6.0 on 2025-12-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_add_database_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="course",
            name="course_slug_idx",
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="course_active_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="course_instructor_idx",
        ),
        migrations.RemoveIndex(
            model_name="enrollment",
            name="enrollment_user_course_idx",
        ),
        migrations.RemoveIndex(
            model_name="lesson",
            name="lesson_slug_idx",
        ),
        migrations.RemoveIndex(
            model_name="progress",
            name="progress_user_lesson_idx",
        ),
        migrations.RemoveIndex(
            model_name="progress",
            name="progress_completed_user_idx",
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_duration",
            field=models.DurationField(
                blank=True, help_text="Video duration in HH:MM:SS format", null=True
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_size",
            field=models.PositiveIntegerField(
                blank=True, help_text="Video file size in bytes", null=True
            ),
        ),
    ]
