# Generated by Django 5.2.7 on 2025-10-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='closing_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the course enrollment closes', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='opening_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the course becomes available for enrollment', null=True),
        ),
    ]
